application: spleaner
version: 1
runtime: python
api_version: 1

handlers:
- url: /i
  static_dir: static/i

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /_ereporter/.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: .*
  script: main.py