application: spleaner
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css/

- url: /i
  static_dir: static/i/

- url: /favicon.ico
  static_files: i/favicon.ico
  upload: i/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /js
  static_dir: static/js/

- url: /s
  static_dir: static/

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /.*
  script: main.py